### ISSUE TITLE
Project Development

### ISSUE THREAD

**Issue by tiagomenegaz** [tmmgarcia/doom-fire#1]
Project Development

### Base
- [x] file structure (index + JS) #2 

### Data Structures

- [x] create basic functions (fireStructure + firePropagation + fireRendering) #3
- [x] create fire canvas #4
_______

## Rendering 
- [x] create fire using fire's color pallete #5
- [x] calculate fire propagation #5
- [x] refresh table #5
- [x] print table #5
- [x] calculate fire #5
